### ISSUE TITLE
Use LIMIT for queries to Mimir

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#23] opened 2018-06-09 01:32 UTC
Vizier shouldn't be trying to grab all of the data from Mimir at once.  Cache it, sure, but right now running the full spreadsheet query is creating a huge amount of lag.

**Comment by heikomuller** [comment] 2018-06-13 22:36
Can you give a few more details on how you envision the use of LIMIT here?

**Comment by okennedy** [comment] 2018-06-13 23:42
For displaying paginated results from X to X+Y, do

SELECT ... LIMIT Y OFFSET X

(My memory of the semantics might be wrong)

-O

**Comment by heikomuller** [comment] 2018-06-14 18:57
Ok. The problem is that the row positions are currently not in the database, only the unique row id's are. Managing the positions externally had advantages for implementing operators that insert/delete/move rows (in particular for SORT). Nevertheless, we could add the position to the database if you insist. This would also require to sort the whole table on the row position every time we want to get a subset of the rows which might have implications on the performance as well.

I made a few changes that should improve performance for now and may satisfy you.

- When adding a new cell to a notebook the full set of rows was fetched twice before. This is gone now. Adding cells to a notebook should be faster.

- What we do know when we fetch the rows for a spreadsheet page is the (min,max) row id. I added a WHERE clause that fetches only rows within this range. On average I would expect that this performs better than using SELECT *.

I close this issue for now. Should you feel strong about using LIMIT please create a new issue in the web-api repository.

**Closed by heikomuller** 2018-06-14 18:57 UTC
Labels: enhancement, priority

**Comment by okennedy** [comment] 2018-06-14 23:19
The `SELECT WHERE low < ROWID < high` seems functionally equivalent to what I was suggesting for the LIMIT clause.  This seems reasonable enough for now.  @mrb24 can you deploy it, and we'll see what it looks like.
