### ISSUE TITLE
Get additional metadata while inferring data type through Mimir

### ISSUE THREAD

**Issue by soniacq** [VizierDB/web-ui#236] opened 2020-07-06 20:13 UTC
This is how the structure of the metadata would look like (of course it can change):

{ 'columns': 
 [ {'name': 'AGE',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': [],
   'unclean_values_ratio': 0.0,
   'num_distinct_values': 25,
   'mean': 31.27777777777778,
   'stddev': 7.102859796163133,
   'plot': {'type': 'histogram_numerical',
    'data': [{'count': 9, 'bin_start': 20.0, 'bin_end': 23.5},
     {'count': 13, 'bin_start': 23.5, 'bin_end': 27.0},
     {'count': 15, 'bin_start': 27.0, 'bin_end': 30.5},
     {'count': 10, 'bin_start': 30.5, 'bin_end': 34.0},
     {'count': 11, 'bin_start': 34.0, 'bin_end': 37.5},
     {'count': 5, 'bin_start': 37.5, 'bin_end': 41.0},
     {'count': 7, 'bin_start': 41.0, 'bin_end': 44.5},
     {'count': 1, 'bin_start': 44.5, 'bin_end': 48.0},
     {'count': 0, 'bin_start': 48.0, 'bin_end': 51.5},
     {'count': 1, 'bin_start': 51.5, 'bin_end': 55.0}]},
   'coverage': [{'range': {'gte': 21.0, 'lte': 29.0}},
    {'range': {'gte': 30.0, 'lte': 38.0}},
    {'range': {'gte': 40.0, 'lte': 55.0}}]},
.
.
.
  {'name': 'OWNRENT',
   'structural_type': 'http://schema.org/Integer',
   'semantic_types': ['http://schema.org/Boolean'],
   'unclean_values_ratio': 0.0,
   'num_distinct_values': 2,
   'mean': 0.375,
   'stddev': 0.4841229182759271,
   'plot': {'type': 'histogram_numerical',
    'data': [{'count': 45, 'bin_start': 0.0, 'bin_end': 0.1},
     {'count': 0, 'bin_start': 0.1, 'bin_end': 0.2},
     {'count': 0, 'bin_start': 0.2, 'bin_end': 0.30000000000000004},
     {'count': 0, 'bin_start': 0.30000000000000004, 'bin_end': 0.4},
     {'count': 0, 'bin_start': 0.4, 'bin_end': 0.5},
     {'count': 0, 'bin_start': 0.5, 'bin_end': 0.6000000000000001},
     {'count': 0,
      'bin_start': 0.6000000000000001,
      'bin_end': 0.7000000000000001},
     {'count': 0, 'bin_start': 0.7000000000000001, 'bin_end': 0.8},
     {'count': 0, 'bin_start': 0.8, 'bin_end': 0.9},
     {'count': 27, 'bin_start': 0.9, 'bin_end': 1.0}]},
   'coverage': [{'range': {'gte': 0.0, 'lte': 0.0}},
    {'range': {'gte': 1.0, 'lte': 1.0}}]}],
 'sample': 'AVGEXP,AGE,INCOME,INCOMESQ,OWNRENT\n15.0,34,4.5,20.25,1\n137.87,31,2.54,6.4516,0\n256.66,31,3.95,15.6025,1\n78.87,29,2.45,6.0025,1\n248.72,40,4.0,16.0,1\n548.03,40,10.0,100.0,1\n552.72,21,2.47,6.1009,1\n53.65,23,2.59,6.7081,0\n9.58,38,2.6,6.76,0\n319.49,36,2.0,4.0,0\n34.13,24,2.8,7.84,0\n95.8,25,3.0,9.0,0\n27.78,27,2.28,5.1984,0\n306.03,41,6.0,36.0,0\n642.47,25,3.07,9.4249,0\n98.46,25,2.88,8.2944,0\n258.55,36,3.05,9.3025,0\n101.68,33,2.55,6.5025,0\n49.56,29,2.4,5.76,0\n235.57,41,7.24,52.4176,1\n'}

**Comment by okennedy** [comment] 2020-07-07 03:18
I'll take a look at this after the SIGMOD deadline tomorrow.

**Comment by okennedy** [comment] 2020-07-08 16:21
@soniacq , a few clarifications about how you'd like this to work.  

Based on the inciting email chain, the implication was that we wanted to add support for Vizier to add dataset/column annotations (along with optional propagation rules for specific types of annotations).  This would mean that, in Mimir, we'd have setters/getters for properties that, unlike the rest of the data would be considered mutable.

The way this ticket is phrased makes it sound like you're asking for Mimir to compute statistics itself (e.g., as properties).  This is certainly reasonable, and could be included as an additional way to populate some of these properties on data load.

So to be clear, is the priority here property setter/getters, or is it stat-gathering functionality in Mimir (I'll aim to get both done).

**Comment by okennedy** [comment] 2020-07-08 20:38
After the call, it seems a bit of rethinking is appropriate.  Currently, the proposed changes include the following modifications to the vizier-api datastore API (cc: @heikomuller )

* remove `get_annotation` method
* remove `set_annotation` method
* add `get_property` method (this behaves like the FS `get_annotation`)
* add `get_properties` method (return all properties)
* `create_dataset` should (if it doesn't already) take a set of properties and persist them with the dataset for later retrieval.
* add `get_caveats` method (this behaves like the Mimir `get_annotation`)

**Comment by okennedy** [comment] 2020-07-10 01:47
@heikomuller: Given our discussions, it sounds like there's going to be a single per-dataset properties dictionary and caveats stored in a backend-specific format.  Given this, the `vizier.datastore.annotation` package seems to be obsolete.  Any objections to me excising it?

**Comment by okennedy** [comment] 2020-07-10 18:26
Now that I've gotten waist deep in the code, I'm able to make the proposed changes a little more concrete:

### `vizier.datastore.base.Datastore` and its subclasses
1. Remove `get_annotation`
2. Remove `update_annotation`
3. Rename `attributes` parameter in `create_dataset` to `properties`, and change type to `dict`
4. Add `get_caveats`, `get_properties` methods
```
    @abstractmethod
    def get_caveats(self, identifier, column_id=None, row_id=None):
        """Get list of annotations for a resources of a given dataset. If only
        the column id is provided annotations for the identifier column will be
        returned. If only the row identifier is given all annotations for the
        specified row are returned. Otherwise, all annotations for the specified
        cell are returned. If both identifier are None all annotations for the
        dataset are returned.

        Parameters
        ----------
        column_id: int, optional
            Unique column identifier
        row_id: int, optiona
            Unique row identifier

        Returns
        -------
        list of vizier.datastore.annotation.base.DatasetAnnotation
        """
        raise NotImplementedError


    @abstractmethod
    def get_properties(self, identifier):
        """Get list of properties for a resources of a given dataset. 

        Parameters
        ----------
        identifier: 

        Returns
        -------
        dict
        """
        raise NotImplementedError
```

### `vizier.datastore.dataset.DatasetHandle` and its subclasses
1. remove `get_annotation`
2. remove `update_annotation`
3. Add `get_caveats`, `get_properties` methods
```

    @abstractmethod
    def get_caveats(self, column_id=None, row_id=None):
        """Get all annotations for a given dataset resource. If both identifier
        are None all dataset annotations are returned.

        Parameters
        ----------
        column_id: int, optional
            Unique column identifier
        row_id: int, optional
            Unique row identifier

        Returns
        -------
        list(vizier.datastpre.annotation.base.DatasetAnnotation)
        """
        raise NotImplementedError

    @abstractmethod
    def get_properties(self):
        """Get all annotations for a given dataset resource. If both identifier
        are None all dataset annotations are returned.

        Parameters
        ----------

        Returns
        -------
        dict
        """
        raise NotImplementedError
```

### `vizier.datastore.annotation.dataset.DatasetMetadata`
1. Remove this class

### `vizier.api.webservice.server`
1. Remove `get_dataset_annotations` route
2. Add `get_dataset_caveats` route, linked to the corresponding datastore API method
3. Add `get_dataset_properties` route, linked to the corresponding datastore API method

@heikomuller , Does this seem reasonable?

**Comment by heikomuller** [comment] 2020-07-13 15:01
In the interest of simplifying the API we could get rid of `get_caveats` and `get_properties` method in either the `Datastore` or the `DatasetHandle`. Alternatively, don't make the methods abstract in the data store since there seems to be a clear default implementation (e.g., `self.get_datset(identifier).get_caveats()`).

**Comment by heikomuller** [comment] 2020-07-13 15:04
What was the conclusion of your discussion about updating caveats and properties? To create/update/delete caveats do we use cells similar to the `CommentLens` in Mimir? Can properties only be created/updated/deleted when a new dataset version is created in the data store?

**Comment by heikomuller** [comment] 2020-07-13 15:19
Is there a particular reason why the `get_properties` method for the `DatasetHandle` does not have any parameters? I was under the impression the properties can either be set for a whole dataset or for a dataset column.

**Comment by okennedy** [comment] 2020-07-13 15:22
> What was the conclusion of your discussion about updating caveats and properties? To create/update/delete caveats do we use cells similar to the `CommentLens` in Mimir? Can properties only be created/updated/deleted when a new dataset version is created in the data store?

This is correct.  I think we want both Properties and Caveats to be immutable.

> Is there a particular reason why the `get_properties` method for the `DatasetHandle` does not have any parameters? I was under the impression the properties can either be set for a whole dataset or for a dataset column.

I'm largely following Sonia's suggested schema above.  How about, by convention, the property "columns" is a dictionary mapping column names to per-column property dictionaries?

**Comment by heikomuller** [comment] 2020-07-13 16:08
The problem is that column names are not necessarily unique. This should then be a mapping of column identifier to dictionaries. Personally, I would prefer to have properties as key value pairs (I believe as we discussed earlier), e.g. `get_properties(self, column_id=None, key)`. That would make it easier for example to maintain results from different data profiler (each having their own unique identifier/key). It would also make it easier for cells that operate on properties that were created by a particular (e.g.) profiler.

**Comment by okennedy** [comment] 2020-07-13 16:34
> The problem is that column names are not necessarily unique. This should then be a mapping of column identifier to dictionaries. 

How about making `columns` instead a positionally-indexed array of objects, with a mandatory `name` field.  This makes it possible to look up columns by name, as well as by position.  In principle, we could also add an `identifier` field with a unique column identifier, if you think it's necessary.

> Personally, I would prefer to have properties as key value pairs (I believe as we discussed earlier), e.g. get_properties(self, column_id=None, key). That would make it easier for example to maintain results from different data profiler (each having their own unique identifier/key). It would also make it easier for cells that operate on properties that were created by a particular (e.g.) profiler.

Supporting multiple profilers working in tandem seems like it would add a lot of complexity (anything that uses profiler output would need to be modified to account for each individual profiler).  Simultaneously, there wouldn't be much benefit in the typical use case, since the only really compelling reason to run multiple profilers would be for one to fill in the missing gaps in the output of another.

I would propose instead that we define a common properties schema and map each profiler's output into it (e.g., using @soniacq 's example above as a starting point).  If we need to run multiple profilers, we merge outputs together:
- *Pro*: Keeps code that needs to read profiler output simple, since it doesn't need to be modified every time we add a new profiler.  Modifications are only needed when a new profiler adds a feature that the consuming code benefits from.
- *Pro*: Keeps logic for merging conflicting profiler outputs in one place (at the point where the profilers are run), rather than forcing us to add resolution logic into each and every consumer of this data.
- *Con*: Makes it difficult to create data displays that communicate conflicting profiler output (although note that we can achieve a similar effect by applying a caveat at the time of the conflict)

**Comment by okennedy** [comment] 2020-07-13 16:43
One added idea that could merge both of these approaches: What if we did something like:
```
def get_properties(self, column_id = None, profiler = None) -> Dict[String,Any]
```
This is analogous to your proposal, where each profiler's output is present, but with two changes:
1. We enforce a common properties schema as I proposed, and
2. We require anything that sets properties to add a 'default' output that indicates which profiler's output to use at each point.  The encoded schema could use `$ref` objects to avoid duplicating things.  For example:
```
{
  "alices_profiler" : {
    "columns" : [
      { "name" : "A", "id" : 1, ... },
      ...
    ], ...
 "bobs_profiler" : { 
    "sample" : [ ... ], 
    ...
  },
  ...
```
And then one of:
```
  "default" : { "$ref" : "#/alices_profiler" } }
```
or
```
  "default" : { 
    "columns" : { "$ref" : "#/alices_profiler/columns" }, 
    "sample" : { "$ref" : "#/bobs_profiler/sample },
    ...
  }
```

**Comment by soniacq** [comment] 2020-07-14 16:12
> How about making columns instead a positionally-indexed array of objects, with a mandatory name field. This makes it possible to look up columns by name, as well as by position. In principle, we could also add an identifier field with a unique column identifier, if you think it's necessary.

I agree with this. Actually, this was the original proposal. I accidentally removed the open square bracket in the proposed schema above.

> ... Simultaneously, there wouldn't be much benefit in the typical use case, since the only really compelling reason to run multiple profilers would be for one to fill in the missing gaps in the output of another.

There could be cases where the profilers 'do' the same things (support for same datatypes), but the user has a preference for one of them (maybe because he/she has already used in the past, etc). In that case, the user can choose one of the profilers, and not combine them.

> I would propose instead that we define a common properties schema and map each profiler's output into it (e.g., using @soniacq 's example above as a starting point). If we need to run multiple profilers, we merge outputs together:

Agree.

**Comment by heikomuller** [comment] 2020-07-14 21:35
I think I'm one meta-level above. To me, the properties are a mechanism for anyone to associate a piece of metadata with a dataset or any (subset of) dataset column(s). Metadata can be structured but I would not enforce a global schema on the object (other than that it is a dictionary and values are dictionaries, lists, or scalar values, e.g. a Json object?). The schema should be up to the creator (profiler).

Obviously, if one wants others to make use of the metadata the specific schema has to be documented. For me these are **metadata types**. This is where @soniacq 's example comes into play. The datamart profiler produces metadata of (at least one) particular type (schema). Data of this type is currently consumed by the front-end to render dataset properties and some charts. Anyone that wants to use an alternative profiler but still wants their results to be rendered in the front-end would need to produce metadata of that particular type. If there are more than one profiler that produce metadata of the same type the user has to chose one (currently in the LOAD cell).

A profiler can then produce one or more metadata objects of different types (if I understand it correctly, the datamart profiler not only provides information about columns but also the full dataset, e.g., a geographical region that may be assigned to the dataset). And we can have multiple profiler that produce metadata of different types. The type could be the key that is associated with the metadata. If the column information is in the metadata object the API would then be `get_property(self, key)` and the result is a dictionary.

**Comment by okennedy** [comment] 2020-07-17 00:00
I may have expressed myself poorly, but I think we're on the same page: I was proposing that we define and document a set of metadata typing conventions necessary to support baseline functionality (like, e.g., the web-ui's profile views).  I think the discussion may have derailed a little when we started discussing how to resolve conflicts between two profilers that both provide the same key/type, but I'm comfortable saying that we're only allowed to run one profiler for now.

**Comment by okennedy** [comment] 2020-07-23 17:08
@soniacq : While waiting on @mrb24 to merge these in, fixes are available in the following two branches
* https://github.com/VizierDB/web-api-async/tree/add-dataset-properties
* https://github.com/UBOdin/mimir-api/tree/add-dataset-properties

**Closed** 2020-09-23 17:52 UTC
Labels: Mimir-API, Vizier-API, enhancement, priority
